apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://Helm.elastic.co'
    targetRevision: 7.12.0
    chart: elasticsearch
    helm:
      parameters:
        - name: replicas
          value: '2'
        - name: esJavaOpts
          value: '-Xmx512m -Xms512m'
        - name: volumeClaimTemplate.resources.requests.storage
          value: 1Gi
        - name: resources.limits.cpu
          value: 1
        - name: resources.requests.cpu
          value: 200m
        - name: resources.limits.memory
          value: 2G
        - name: resources.requests.memory
          value: 256M
  project: operation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
          - CreateNamespace=true      
