apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://Helm.elastic.co'
    targetRevision: 7.12.0
    chart: filebeat
    helm:
      values: |
        daemonset:
          filebeatConfig:
            filebeat.yml: |
              filebeat.inputs:
              - type: container
                paths:
                  - /var/log/containers/*.log
                processors:
                - add_kubernetes_metadata:
                    host: ${NODE_NAME}
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers/"
                - drop_event.when:
                    or:
                    - equals:
                        kubernetes.namespace: "argocd"
                    - equals:
                        kubernetes.namespace: "cert-manager"
                    - equals:
                        kubernetes.namespace: "internal-ingress-nginx"
                    - equals:
                        kubernetes.namespace: "kube-public"
                    - equals:
                        kubernetes.namespace: "kube-system"
                    - equals:
                        kubernetes.namespace: "local-path-storage"
                    - equals:
                        kubernetes.namespace: "logging"
                    - equals:
                        kubernetes.namespace: "metalib-system"
                    - equals:
                        kubernetes.namespace: "monitoring"
                    - equals:
                        kubernetes.namespace: "nfs-provisioner"
                    - equals:
                        kubernetes.namespace: "public-ingress-nginx"                       
              output.elasticsearch:
                host: '${NODE_NAME}'
                hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
  project: operation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
