apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: gpu
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 4.1.0
    chart: intel-gpu-plugin
  project: operation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
          - CreateNamespace=true     
