apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-kibana
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://Helm.elastic.co'
    targetRevision: 7.12.0
    chart: kibana
  project: operation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
