apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  destination:
    namespace: local-path-provisioner
    server: 'https://kubernetes.default.svc'
  project: operation
  source:
    path: v1.19.9/local-path-provisioner
    repoURL: 'https://github.com/jackiefong/bootstrap.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
